In [3]:
# Pandas - удобная надстройка над NumPy. В NumPy индексы - целые числа, в Pandas - всё что угодно (время, строки и т.д.).
# Series
# DataFrame
# Index
import numpy as np
import pandas as pd

In [19]:
data = pd.Series([0.25, 0.5, 0.75, 1.0]) #  Если упростить до предела: Series = ndarray + Index
print(data)

print(data.values)
print(type(data.values))

print(data.index)
print(type(data.index))

print(data[1])
print(data[1:3])

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64
[0.25 0.5  0.75 1.  ]
<class 'numpy.ndarray'>
RangeIndex(start=0, stop=4, step=1)
<class 'pandas.core.indexes.range.RangeIndex'>
0.5
1    0.50
2    0.75
dtype: float64


In [4]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = ['a', 'b', 'c', 'd'])
print(data)

print(type(data.index[0]))
print(data['a'])
print(data['b':'d']) # the last element is included (not like with inreger slices)

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
<class 'str'>
0.25
b    0.50
c    0.75
d    1.00
dtype: float64


In [23]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = [1, 10, 7, 'd'])
print(data)

print(type(data.index))
print(type(data.index[0]))
print(type(data.index[3]))
print(data.index)

print(data[1])
print(data['d'])
print(data[10:'d'])

1     0.25
10    0.50
7     0.75
d     1.00
dtype: float64
<class 'pandas.core.indexes.base.Index'>
<class 'int'>
<class 'str'>
Index([1, 10, 7, 'd'], dtype='object')
0.25
1.0
10    0.50
7     0.75
d     1.00
dtype: float64


In [7]:
my_dict = {
    'A': 10,
    'B': 20,
    'C': 30,
    'D': 40,
    'E': 50
}

data_dict = pd.Series(my_dict)
print(data_dict)

print(data_dict['b':'d']) # 'dict' with slices

A    10
B    20
C    30
D    40
E    50
dtype: int64
Series([], dtype: int64)


In [29]:
# Conclusions about how to create Series?

# 1. Arrays
data = pd.Series([0.25, 0.5, 0.75, 1.0])
print(data)

data = pd.Series(5, index=[10, 20, 30])
print(data, end='\n\n')

# 2. Dictionaries
data_dict = pd.Series(my_dict)
print(data_dict)

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64
10    5
20    5
30    5
dtype: int64

A    10
B    20
C    30
D    40
E    50
dtype: int64


In [63]:
# DataFrame - n-dimensional massive, Series - 1-d massive. DataFrame consists of some Series
my_dict1 = {
    'A': 10,
    'B': 20,
    'C': 30,
    'D': 40,
    'E': 50,
   #'N' : 60
}

my_dict2 = {
    'A': 11,
    'B': 21,
    'C': 31,
    'D': 41,
    'E': 51,
    'V': 60
}

data_dict1 = pd.Series(my_dict1)
print(data_dict1)

data_dict2 = pd.Series(my_dict2)
print(data_dict2)


df = pd.DataFrame({'dict_01': data_dict1, 'dict_02': data_dict2})
print(df)

print(df.values)
print(type(df.values))

print(df.columns)
print(type(df.columns))

print(df.index)
print(type(df.index))

print(df['dict_01'])
print(df['dict_02'])

A    10
B    20
C    30
D    40
E    50
dtype: int64
A    11
B    21
C    31
D    41
E    51
V    60
dtype: int64
   dict_01  dict_02
A     10.0       11
B     20.0       21
C     30.0       31
D     40.0       41
E     50.0       51
V      NaN       60
[[10. 11.]
 [20. 21.]
 [30. 31.]
 [40. 41.]
 [50. 51.]
 [nan 60.]]
<class 'numpy.ndarray'>
Index(['dict_01', 'dict_02'], dtype='object')
<class 'pandas.core.indexes.base.Index'>
Index(['A', 'B', 'C', 'D', 'E', 'V'], dtype='object')
<class 'pandas.core.indexes.base.Index'>
A    10.0
B    20.0
C    30.0
D    40.0
E    50.0
V     NaN
Name: dict_01, dtype: float64
A    11
B    21
C    31
D    41
E    51
V    60
Name: dict_02, dtype: int64


In [17]:
df = pd.DataFrame({'dict_01': data_dict1}) # Series - 1-d massive, but DataFrame is 2-d (analogy with numpy: array and .reshape)
print(df)
print(df.values)

df = pd.DataFrame(data_dict1, columns=['rrr'])
print(df)

   dict_01
A       10
B       20
C       30
D       40
E       50
[[10]
 [20]
 [30]
 [40]
 [50]]
   rrr
A   10
B   20
C   30
D   40
E   50


In [22]:
print(pd.DataFrame([{'a': i, 'b': 2 * i} for i in range(4)]))

# NaN - Not a Number
print(pd.DataFrame(np.zeros(3)))

   a  b
0  0  0
1  1  2
2  2  4
3  3  6
     0
0  0.0
1  0.0
2  0.0


In [24]:
# Index - способ сослаться (reference) на данные в Series или DataFrame
index = pd.Index([2, 5, 3, 5, 71])
print(index)
print(type(index))

print(index[1])
print(index[::2])

# index[1] = 21 - Index is an immutable object!

Int64Index([2, 5, 3, 5, 71], dtype='int64')
<class 'pandas.core.indexes.numeric.Int64Index'>
5
Int64Index([2, 3, 71], dtype='int64')


In [44]:
# Index is familiar with a built-in Python's set
index1 = pd.Index([2, 5, 3, 5, 71])
index2 = pd.Index([1, 2, 5, 71, 4])

print(index1.intersection(index2)) # &
print(index1.union(index2)) # |
print(index1.symmetric_difference(index2)) # ^ and etc.

Int64Index([2, 5, 71], dtype='int64')
Int64Index([1, 2, 3, 4, 5, 5, 71], dtype='int64')
Int64Index([1, 3, 4], dtype='int64')


In [46]:
# Numpy
# индексация arr[1,2]
# срезы arr[:, 1:4]
# маскирование arr[arr > 5]
# arr[0, [1,5]]   arr[:, [1,5]]

In [81]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = ['a', 'b', 'c', 'd'])
print(data['a'])

print(data)
print('a' in data)
print('a1' in data)

data['a'] = 99
data['a1'] = 999
print(data)

print(data['c': 'a1']) # explicit slice
print(data[2:]) # Absolutely the same (implicit slice)
print(data[(data > 0.3) & (data < 0.8)])

print(data[['c', 'a']]) # print(data[[2, 0]])
#data.iloc - keys, data.loc - values

0.25
a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
True
False
a      99.00
b       0.50
c       0.75
d       1.00
a1    999.00
dtype: float64
c       0.75
d       1.00
a1    999.00
dtype: float64
c       0.75
d       1.00
a1    999.00
dtype: float64
b    0.50
c    0.75
dtype: float64
c     0.75
a    99.00
dtype: float64


In [123]:
# атрибуты-индексаторы
print(df, end='\n\n')

print(df['dict_01'], end='\n\n')
print(df.dict_01, end='\n\n') # the same

df['new'] = df['dict_01']
df['new1'] = df['dict_01'] / df.dict_02
print(df, end='\n\n')

print(df.values, end='\n\n')
print(df['dict_01'], end='\n\n') # column
print(df.values[0], end='\n\n') # row

   dict_01  dict_02   new      new1
A     10.0       11  10.0  0.909091
B     20.0       21  20.0  0.952381
C     30.0       31  30.0  0.967742
D     40.0       41  40.0  0.975610
E     50.0       51  50.0  0.980392
V      NaN       60   NaN       NaN

A    10.0
B    20.0
C    30.0
D    40.0
E    50.0
V     NaN
Name: dict_01, dtype: float64

A    10.0
B    20.0
C    30.0
D    40.0
E    50.0
V     NaN
Name: dict_01, dtype: float64

   dict_01  dict_02   new      new1
A     10.0       11  10.0  0.909091
B     20.0       21  20.0  0.952381
C     30.0       31  30.0  0.967742
D     40.0       41  40.0  0.975610
E     50.0       51  50.0  0.980392
V      NaN       60   NaN       NaN

[[10.         11.         10.          0.90909091]
 [20.         21.         20.          0.95238095]
 [30.         31.         30.          0.96774194]
 [40.         41.         40.          0.97560976]
 [50.         51.         50.          0.98039216]
 [        nan 60.                 nan         nan]]

A   

In [127]:
print(df, end='\n\n')
print(df.loc['A':'C', :'dict_02'], end='\n\n')
print(df.iloc[0:3, :2], end='\n\n') #the same

print(df.loc[df.dict_02 > 30, ['new1', 'dict_01']], end='\n\n')
df.loc[df.dict_02 > 30, ['new1', 'dict_01']] = 36
print(df)

   dict_01  dict_02   new       new1
A     10.0       11  10.0   0.909091
B     20.0       21  20.0   0.952381
C     36.0       31  30.0  36.000000
D     36.0       41  40.0  36.000000
E     36.0       51  50.0  36.000000
V     36.0       60   NaN  36.000000

   dict_01  dict_02
A     10.0       11
B     20.0       21
C     36.0       31

   dict_01  dict_02
A     10.0       11
B     20.0       21
C     36.0       31

   new1  dict_01
C  36.0     36.0
D  36.0     36.0
E  36.0     36.0
V  36.0     36.0

   dict_01  dict_02   new       new1
A     10.0       11  10.0   0.909091
B     20.0       21  20.0   0.952381
C     36.0       31  30.0  36.000000
D     36.0       41  40.0  36.000000
E     36.0       51  50.0  36.000000
V     36.0       60   NaN  36.000000


In [150]:
rng = np.random.default_rng(seed=1)
s = pd.Series(rng.integers(0, 10, 6))
print(s, end='\n\n')

print(np.exp(s), end='\n\n')

df = pd.DataFrame(rng.integers(0, 10, (3,4)), columns=['A','B','C','D'])
print(df, end='\n\n')
print(np.sin(df * 4), end='\n\n')

0    4
1    5
2    7
3    9
4    0
5    1
dtype: int64

0      54.598150
1     148.413159
2    1096.633158
3    8103.083928
4       1.000000
5       2.718282
dtype: float64

   A  B  C  D
0  8  9  2  3
1  8  4  2  8
2  2  4  6  5

          A         B         C         D
0  0.551427 -0.991779  0.989358 -0.536573
1  0.551427 -0.287903  0.989358  0.551427
2  0.989358 -0.287903 -0.905578  0.912945



In [185]:
# Индексы не просто сохраняются, а согласовываются
my_dict1 = {
    'A': 10,
    'B': 20,
    'C': 30,
    'D': 40,
    'E': 50,
   #'N' : 60
}

my_dict2 = {
    'A': 11,
    'B': 21,
    'C': 31,
    'D': 41,
    'E': 51,
    'V': 60
}

df = pd.DataFrame({'dict_01': data_dict1, 'dict_02': data_dict2})
print(df, end='\n\n')

print(data_dict1 + data_dict2, end='\n\n')
print(np.add(data_dict1, data_dict2), end='\n\n')
print(data_dict1.add(data_dict2, fill_value=5), end='\n\n') # fill_value can replace Nans

   dict_01  dict_02
A     10.0       11
B     20.0       21
C     30.0       31
D     40.0       41
E     50.0       51
V      NaN       60

A     21.0
B     41.0
C     61.0
D     81.0
E    101.0
V      NaN
dtype: float64

A     21.0
B     41.0
C     61.0
D     81.0
E    101.0
V      NaN
dtype: float64

A     21.0
B     41.0
C     61.0
D     81.0
E    101.0
V     65.0
dtype: float64



In [191]:
print(df, end='\n\n')
df1 = pd.DataFrame({'dict_02': data_dict1, 'dict_03': data_dict2})
print(df1, end='\n\n')
print(df + df1, end='\n\n') #Lot's of Nan
print(df.add(df1, fill_value = 5), end='\n\n')

   dict_01  dict_02
A     10.0       11
B     20.0       21
C     30.0       31
D     40.0       41
E     50.0       51
V      NaN       60

   dict_02  dict_03
A     10.0       11
B     20.0       21
C     30.0       31
D     40.0       41
E     50.0       51
V      NaN       60

   dict_01  dict_02  dict_03
A      NaN     21.0      NaN
B      NaN     41.0      NaN
C      NaN     61.0      NaN
D      NaN     81.0      NaN
E      NaN    101.0      NaN
V      NaN      NaN      NaN

   dict_01  dict_02  dict_03
A     15.0     21.0     16.0
B     25.0     41.0     26.0
C     35.0     61.0     36.0
D     45.0     81.0     46.0
E     55.0    101.0     56.0
V      NaN     65.0     65.0



In [216]:
A = rng.integers(10, size=(3,4))
print(A, end='\n\n')
print(A[0], end='\n\n')
print(A - A[0], end='\n\n')

df = pd.DataFrame(A, columns=['A','B','C','D'])
print(df, end='\n\n')
print(df - df.iloc[0], end='\n\n')
print(df.subtract(df['A'], axis=0), end='\n\n')

[[0 8 5 3]
 [9 9 0 6]
 [8 6 6 5]]

[0 8 5 3]

[[ 0  0  0  0]
 [ 9  1 -5  3]
 [ 8 -2  1  2]]

   A  B  C  D
0  0  8  5  3
1  9  9  0  6
2  8  6  6  5

   A  B  C  D
0  0  0  0  0
1  9  1 -5  3
2  8 -2  1  2

   A  B  C  D
0  0  8  5  3
1  0  0 -9 -3
2  0 -2 -2 -3

