In [70]:
# Pandas - удобная надстройка над NumPy. В NumPy индексы - целые числа, в Pandas - всё что угодно (время, строки и т.д.).
# Series
# DataFrame
# Index
import numpy as np
import pandas as pd

In [71]:
data = pd.Series([0.25, 0.5, 0.75, 1.0]) #  Если упростить до предела: Series = ndarray + Index
print(data)

print(data.values)
print(type(data.values))

print(data.index)
print(type(data.index))

print(data[1])
print(data[1:3])

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64
[0.25 0.5  0.75 1.  ]
<class 'numpy.ndarray'>
RangeIndex(start=0, stop=4, step=1)
<class 'pandas.core.indexes.range.RangeIndex'>
0.5
1    0.50
2    0.75
dtype: float64


In [72]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = ['a', 'b', 'c', 'd'])
print(data)

print(type(data.index[0]))
print(data['a'])
print(data['b':'d']) # the last element is included (not like with inreger slices)

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
<class 'str'>
0.25
b    0.50
c    0.75
d    1.00
dtype: float64


In [73]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = [1, 10, 7, 'd'])
print(data)

print(type(data.index))
print(type(data.index[0]))
print(type(data.index[3]))
print(data.index)

print(data[1])
print(data['d'])
print(data[10:'d'])

1     0.25
10    0.50
7     0.75
d     1.00
dtype: float64
<class 'pandas.core.indexes.base.Index'>
<class 'int'>
<class 'str'>
Index([1, 10, 7, 'd'], dtype='object')
0.25
1.0
10    0.50
7     0.75
d     1.00
dtype: float64


In [74]:
my_dict = {
    'A': 10,
    'B': 20,
    'C': 30,
    'D': 40,
    'E': 50
}

data_dict = pd.Series(my_dict)
print(data_dict)

print(data_dict['b':'d']) # 'dict' with slices

A    10
B    20
C    30
D    40
E    50
dtype: int64
Series([], dtype: int64)


In [75]:
# Conclusions about how to create Series?

# 1. Arrays
data = pd.Series([0.25, 0.5, 0.75, 1.0])
print(data)

data = pd.Series(5, index=[10, 20, 30])
print(data, end='\n\n')

# 2. Dictionaries
data_dict = pd.Series(my_dict)
print(data_dict)

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64
10    5
20    5
30    5
dtype: int64

A    10
B    20
C    30
D    40
E    50
dtype: int64


In [76]:
# DataFrame - n-dimensional massive, Series - 1-d massive. DataFrame consists of some Series
my_dict1 = {
    'A': 10,
    'B': 20,
    'C': 30,
    'D': 40,
    'E': 50,
   #'N' : 60
}

my_dict2 = {
    'A': 11,
    'B': 21,
    'C': 31,
    'D': 41,
    'E': 51,
    'V': 60
}

data_dict1 = pd.Series(my_dict1)
print(data_dict1)

data_dict2 = pd.Series(my_dict2)
print(data_dict2)


df = pd.DataFrame({'dict_01': data_dict1, 'dict_02': data_dict2})
print(df)

print(df.values)
print(type(df.values))

print(df.columns)
print(type(df.columns))

print(df.index)
print(type(df.index))

print(df['dict_01'])
print(df['dict_02'])

A    10
B    20
C    30
D    40
E    50
dtype: int64
A    11
B    21
C    31
D    41
E    51
V    60
dtype: int64
   dict_01  dict_02
A     10.0       11
B     20.0       21
C     30.0       31
D     40.0       41
E     50.0       51
V      NaN       60
[[10. 11.]
 [20. 21.]
 [30. 31.]
 [40. 41.]
 [50. 51.]
 [nan 60.]]
<class 'numpy.ndarray'>
Index(['dict_01', 'dict_02'], dtype='object')
<class 'pandas.core.indexes.base.Index'>
Index(['A', 'B', 'C', 'D', 'E', 'V'], dtype='object')
<class 'pandas.core.indexes.base.Index'>
A    10.0
B    20.0
C    30.0
D    40.0
E    50.0
V     NaN
Name: dict_01, dtype: float64
A    11
B    21
C    31
D    41
E    51
V    60
Name: dict_02, dtype: int64


In [77]:
df1 = pd.DataFrame({'dict_01': data_dict1}) # Series - 1-d massive, but DataFrame is 2-d (analogy with numpy: array and .reshape)
print(df)
print(df.values)

df1 = pd.DataFrame(data_dict1, columns=['rrr'])
print(df)

   dict_01  dict_02
A     10.0       11
B     20.0       21
C     30.0       31
D     40.0       41
E     50.0       51
V      NaN       60
[[10. 11.]
 [20. 21.]
 [30. 31.]
 [40. 41.]
 [50. 51.]
 [nan 60.]]
   dict_01  dict_02
A     10.0       11
B     20.0       21
C     30.0       31
D     40.0       41
E     50.0       51
V      NaN       60


In [78]:
print(pd.DataFrame([{'a': i, 'b': 2 * i} for i in range(4)]))

# NaN - Not a Number
print(pd.DataFrame(np.zeros(3)))

   a  b
0  0  0
1  1  2
2  2  4
3  3  6
     0
0  0.0
1  0.0
2  0.0


In [79]:
# Index - способ сослаться (reference) на данные в Series или DataFrame
index = pd.Index([2, 5, 3, 5, 71])
print(index)
print(type(index))

print(index[1])
print(index[::2])

# index[1] = 21 - Index is an immutable object!

Int64Index([2, 5, 3, 5, 71], dtype='int64')
<class 'pandas.core.indexes.numeric.Int64Index'>
5
Int64Index([2, 3, 71], dtype='int64')


In [80]:
# Index is familiar with a built-in Python's set
index1 = pd.Index([2, 5, 3, 5, 71])
index2 = pd.Index([1, 2, 5, 71, 4])

print(index1.intersection(index2)) # &
print(index1.union(index2)) # |
print(index1.symmetric_difference(index2)) # ^ and etc.

Int64Index([2, 5, 71], dtype='int64')
Int64Index([1, 2, 3, 4, 5, 5, 71], dtype='int64')
Int64Index([1, 3, 4], dtype='int64')


In [81]:
# Numpy
# индексация arr[1,2]
# срезы arr[:, 1:4]
# маскирование arr[arr > 5]
# arr[0, [1,5]]   arr[:, [1,5]]

In [82]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = ['a', 'b', 'c', 'd'])
print(data['a'])

print(data)
print('a' in data)
print('a1' in data)

data['a'] = 99
data['a1'] = 999
print(data)

print(data['c': 'a1']) # explicit slice
print(data[2:]) # Absolutely the same (implicit slice)
print(data[(data > 0.3) & (data < 0.8)])

print(data[['c', 'a']]) # print(data[[2, 0]])
#data.iloc - keys, data.loc - values

0.25
a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
True
False
a      99.00
b       0.50
c       0.75
d       1.00
a1    999.00
dtype: float64
c       0.75
d       1.00
a1    999.00
dtype: float64
c       0.75
d       1.00
a1    999.00
dtype: float64
b    0.50
c    0.75
dtype: float64
c     0.75
a    99.00
dtype: float64


In [83]:
# атрибуты-индексаторы
print(df, end='\n\n')

print(df['dict_01'], end='\n\n')
print(df.dict_01, end='\n\n') # the same

df['new'] = df['dict_01']
df['new1'] = df['dict_01'] / df.dict_02
print(df, end='\n\n')

print(df.values, end='\n\n')
print(df['dict_01'], end='\n\n') # column
print(df.values[0], end='\n\n') # row

   dict_01  dict_02
A     10.0       11
B     20.0       21
C     30.0       31
D     40.0       41
E     50.0       51
V      NaN       60

A    10.0
B    20.0
C    30.0
D    40.0
E    50.0
V     NaN
Name: dict_01, dtype: float64

A    10.0
B    20.0
C    30.0
D    40.0
E    50.0
V     NaN
Name: dict_01, dtype: float64

   dict_01  dict_02   new      new1
A     10.0       11  10.0  0.909091
B     20.0       21  20.0  0.952381
C     30.0       31  30.0  0.967742
D     40.0       41  40.0  0.975610
E     50.0       51  50.0  0.980392
V      NaN       60   NaN       NaN

[[10.         11.         10.          0.90909091]
 [20.         21.         20.          0.95238095]
 [30.         31.         30.          0.96774194]
 [40.         41.         40.          0.97560976]
 [50.         51.         50.          0.98039216]
 [        nan 60.                 nan         nan]]

A    10.0
B    20.0
C    30.0
D    40.0
E    50.0
V     NaN
Name: dict_01, dtype: float64

[10.         11.         

In [84]:
print(df, end='\n\n')
print(df.loc['A':'C', :'dict_02'], end='\n\n')
print(df.iloc[0:3, :2], end='\n\n') #the same

print(df.loc[df.dict_02 > 30, ['new1', 'dict_01']], end='\n\n')
df.loc[df.dict_02 > 30, ['new1', 'dict_01']] = 36
print(df)

   dict_01  dict_02   new      new1
A     10.0       11  10.0  0.909091
B     20.0       21  20.0  0.952381
C     30.0       31  30.0  0.967742
D     40.0       41  40.0  0.975610
E     50.0       51  50.0  0.980392
V      NaN       60   NaN       NaN

   dict_01  dict_02
A     10.0       11
B     20.0       21
C     30.0       31

   dict_01  dict_02
A     10.0       11
B     20.0       21
C     30.0       31

       new1  dict_01
C  0.967742     30.0
D  0.975610     40.0
E  0.980392     50.0
V       NaN      NaN

   dict_01  dict_02   new       new1
A     10.0       11  10.0   0.909091
B     20.0       21  20.0   0.952381
C     36.0       31  30.0  36.000000
D     36.0       41  40.0  36.000000
E     36.0       51  50.0  36.000000
V     36.0       60   NaN  36.000000


In [85]:
rng = np.random.default_rng(seed=1)
s = pd.Series(rng.integers(0, 10, 6))
print(s, end='\n\n')

print(np.exp(s), end='\n\n')

df = pd.DataFrame(rng.integers(0, 10, (3,4)), columns=['A','B','C','D'])
print(df, end='\n\n')
print(np.sin(df * 4), end='\n\n')

0    4
1    5
2    7
3    9
4    0
5    1
dtype: int64

0      54.598150
1     148.413159
2    1096.633158
3    8103.083928
4       1.000000
5       2.718282
dtype: float64

   A  B  C  D
0  8  9  2  3
1  8  4  2  8
2  2  4  6  5

          A         B         C         D
0  0.551427 -0.991779  0.989358 -0.536573
1  0.551427 -0.287903  0.989358  0.551427
2  0.989358 -0.287903 -0.905578  0.912945



In [86]:
# Индексы не просто сохраняются, а согласовываются
my_dict1 = {
    'A': 10,
    'B': 20,
    'C': 30,
    'D': 40,
    'E': 50,
   #'N' : 60
}

my_dict2 = {
    'A': 11,
    'B': 21,
    'C': 31,
    'D': 41,
    'E': 51,
    'V': 60
}

df = pd.DataFrame({'dict_01': data_dict1, 'dict_02': data_dict2})
print(df, end='\n\n')

print(data_dict1 + data_dict2, end='\n\n')
print(np.add(data_dict1, data_dict2), end='\n\n')
print(data_dict1.add(data_dict2, fill_value=5), end='\n\n') # fill_value can replace Nans

   dict_01  dict_02
A     10.0       11
B     20.0       21
C     30.0       31
D     40.0       41
E     50.0       51
V      NaN       60

A     21.0
B     41.0
C     61.0
D     81.0
E    101.0
V      NaN
dtype: float64

A     21.0
B     41.0
C     61.0
D     81.0
E    101.0
V      NaN
dtype: float64

A     21.0
B     41.0
C     61.0
D     81.0
E    101.0
V     65.0
dtype: float64



In [87]:
print(df, end='\n\n')
df1 = pd.DataFrame({'dict_02': data_dict1, 'dict_03': data_dict2})
print(df1, end='\n\n')
print(df + df1, end='\n\n') #Lot's of Nan
print(df.add(df1, fill_value = 5), end='\n\n')

   dict_01  dict_02
A     10.0       11
B     20.0       21
C     30.0       31
D     40.0       41
E     50.0       51
V      NaN       60

   dict_02  dict_03
A     10.0       11
B     20.0       21
C     30.0       31
D     40.0       41
E     50.0       51
V      NaN       60

   dict_01  dict_02  dict_03
A      NaN     21.0      NaN
B      NaN     41.0      NaN
C      NaN     61.0      NaN
D      NaN     81.0      NaN
E      NaN    101.0      NaN
V      NaN      NaN      NaN

   dict_01  dict_02  dict_03
A     15.0     21.0     16.0
B     25.0     41.0     26.0
C     35.0     61.0     36.0
D     45.0     81.0     46.0
E     55.0    101.0     56.0
V      NaN     65.0     65.0



In [88]:
A = rng.integers(10, size=(3,4))
print(A, end='\n\n')
print(A[0], end='\n\n')
print(A - A[0], end='\n\n')

df = pd.DataFrame(A, columns=['A','B','C','D'])
print(df, end='\n\n')
print(df - df.iloc[0], end='\n\n')
print(df.subtract(df['A'], axis=0), end='\n\n')

[[0 0 8 7]
 [8 5 8 3]
 [4 7 1 3]]

[0 0 8 7]

[[ 0  0  0  0]
 [ 8  5  0 -4]
 [ 4  7 -7 -4]]

   A  B  C  D
0  0  0  8  7
1  8  5  8  3
2  4  7  1  3

   A  B  C  D
0  0  0  0  0
1  8  5  0 -4
2  4  7 -7 -4

   A  B  C  D
0  0  0  8  7
1  0 -3  0 -5
2  0  3 -3 -1



In [89]:
# Отсутствующие данные
a = np.nan#
a = -99999

# Pandas: 1) NaN, None  2) pd.NA
a = None
print(type(a))

a = np.array([1,2,3])
b = np.array([1, None, 3])
print(a.sum())
# print(b.sum()) --- TypeError

c = np.array([1, np.nan, 3])
print(c.sum()) # smth + np.nan = np.nan

print(np.nansum(c)) # nansum allows us to ignore 'nan'

x = pd.Series([1,2,3,4,5], dtype=int)
print(x)
x[0] = None
x[1] = np.nan
print(x)
print(x.sum())

<class 'NoneType'>
6
nan
4.0
0    1
1    2
2    3
3    4
4    5
dtype: int32
0    NaN
1    NaN
2    3.0
3    4.0
4    5.0
dtype: float64
12.0


In [90]:
'''
Иерархия (Hierarchy) приведения типов (Type Promotion)
bool -> int64 -> float64 (Nan, np.nan) -> object (the most essential, str and other)
'''
x = pd.Series(['1', '2', '3', '4', '5'])
print(x)
x[0] = None
x[1] = np.nan
print(x)

0    1
1    2
2    3
3    4
4    5
dtype: object
0    None
1     NaN
2       3
3       4
4       5
dtype: object


In [91]:
x = pd.Series([1, np.nan, None, 5])
print(x)

0    1.0
1    NaN
2    NaN
3    5.0
dtype: float64


In [92]:
x = pd.Series([1, np.nan, None, 5, pd.NA], dtype='Int32')
print(x)

0       1
1    <NA>
2    <NA>
3       5
4    <NA>
dtype: Int32


In [93]:
x = pd.Series([1, np.nan, None, 5, pd.NA], dtype='Float64')
print(x)

0     1.0
1    <NA>
2    <NA>
3     5.0
4    <NA>
dtype: Float64


In [94]:
# Deleting Nan values from Series
x = pd.Series([1, np.nan, None, 5, pd.NA, 'hello'])
print(x)

print(x.isnull())
print(x.notnull(), end='\n\n')
print(x[x.notnull()], end='\n\n') # 1. masking

print(x.dropna(), end='\n\n') # 2. drop out Nan values

0        1
1      NaN
2     None
3        5
4     <NA>
5    hello
dtype: object
0    False
1     True
2     True
3    False
4     True
5    False
dtype: bool
0     True
1    False
2    False
3     True
4    False
5     True
dtype: bool

0        1
3        5
5    hello
dtype: object

0        1
3        5
5    hello
dtype: object



In [95]:
# Deleting Nan values from DataFrame
x = pd.DataFrame([[pd.NA, np.nan, None], [1,2,3], [2,np.nan,3]])
print(x, end='\n\n')
print(x.dropna(axis=0), end='\n\n') # Non-zero rows
print(x.dropna(axis=1), end='\n\n') # Non-zero columns

print(x.dropna(axis=0,how='all')) # default settings how = 'any'

      0    1    2
0  <NA>  NaN  NaN
1     1  2.0  3.0
2     2  NaN  3.0

   0    1    2
1  1  2.0  3.0

Empty DataFrame
Columns: []
Index: [0, 1, 2]

   0    1    2
1  1  2.0  3.0
2  2  NaN  3.0


In [96]:
x = pd.DataFrame([[pd.NA, np.nan, None], [1,2,3], [2,np.nan,3]])
print(x.dropna(axis=1, thresh=2)) # должно быть минимум N непустых значений, thresh - молотить

      0    2
0  <NA>  NaN
1     1  3.0
2     2  3.0


In [97]:
# how = all - убрать, если все значения отсутствуют
# how = any - убрать, если хотя бы одно значение отсутствуют
# tresh = n - убрать, если хотя бы n значений отсутствуют

In [98]:
x = pd.DataFrame([None, 1000, np.nan, None, 1, 2, 3], dtype='Int32')
print(x, end='\n\n')

print(x.fillna(-999), end='\n\n') # fillna(n) - заменить nan на n
print(x.ffill(), end='\n\n') # Заполнить следующее предыдущим значением, forward
print(x.bfill(), end='\n\n') # Заполнить предыдущее следующим, back

      0
0  <NA>
1  1000
2  <NA>
3  <NA>
4     1
5     2
6     3

      0
0  -999
1  1000
2  -999
3  -999
4     1
5     2
6     3

      0
0  <NA>
1  1000
2  1000
3  1000
4     1
5     2
6     3

      0
0  1000
1  1000
2     1
3     1
4     1
5     2
6     3



In [99]:
x = pd.DataFrame([[pd.NA, np.nan, None], [1,2,3], [2,np.nan,3]])
print(x, end='\n\n')

print(x.ffill(axis=1), end='\n\n')
print(x.bfill(axis=1), end='\n\n')
print(x.ffill(axis=0), end='\n\n')
print(x.bfill(axis=0), end='\n\n')

      0    1    2
0  <NA>  NaN  NaN
1     1  2.0  3.0
2     2  NaN  3.0

      0     1     2
0  <NA>  <NA>  <NA>
1   1.0   2.0   3.0
2   2.0   2.0   3.0

     0    1    2
0  NaN  NaN  NaN
1  1.0  2.0  3.0
2  2.0  3.0  3.0

      0    1    2
0  <NA>  NaN  NaN
1     1  2.0  3.0
2     2  2.0  3.0

   0    1    2
0  1  2.0  3.0
1  1  2.0  3.0
2  2  NaN  3.0



In [100]:
# Иерархическая индексация - Hierarchical indexing or Multindexing
index = [
    ('A1', 2025),
    ('A1', 2026),
    ('A2', 2025),
    ('A2', 2026),
    ('A3', 2025),
    ('A3', 2026),
]

data = [1, 2, 3, 4, 5, 6]
s = pd.Series(data, index=index)
print(s, end = '\n\n')
print(s[[0,2,4]], end = '\n\n')

print(s[[i for i in s.index if i[0] == 'A1']], end = '\n\n') 

(A1, 2025)    1
(A1, 2026)    2
(A2, 2025)    3
(A2, 2026)    4
(A3, 2025)    5
(A3, 2026)    6
dtype: int64

(A1, 2025)    1
(A2, 2025)    3
(A3, 2025)    5
dtype: int64

(A1, 2025)    1
(A1, 2026)    2
dtype: int64



In [101]:
# В index содержится иерархия, которую можно реализовать через Multiindex
mi = pd.MultiIndex.from_tuples(index)
print(mi)

s = s.reindex(mi) # способ перестроить существующий объект (Series или DataFrame) так, чтобы он соответствовал новому индексу mi.
print(s)

MultiIndex([('A1', 2025),
            ('A1', 2026),
            ('A2', 2025),
            ('A2', 2026),
            ('A3', 2025),
            ('A3', 2026)],
           )
A1  2025    1
    2026    2
A2  2025    3
    2026    4
A3  2025    5
    2026    6
dtype: int64


In [102]:
s1 = pd.Series(data, index=mi) # способ создать новый перестроенный объект
print(s1)

A1  2025    1
    2026    2
A2  2025    3
    2026    4
A3  2025    5
    2026    6
dtype: int64


In [103]:
print(s.loc['A1', :])

A1  2025    1
    2026    2
dtype: int64


In [104]:
# .stack() and .unstack()
df = s.unstack()
print(df, end='\n\n')

df = df.stack()
print(df)

    2025  2026
A1     1     2
A2     3     4
A3     5     6

A1  2025    1
    2026    2
A2  2025    3
    2026    4
A3  2025    5
    2026    6
dtype: int64


In [105]:
# одномерный Series может хранить данные с большим числом измерений
index = [
    ('A1', 2025, 1),
    ('A1', 2025, 2),
    ('A1', 2026, 1),
    ('A1', 2026, 2),
    ('A2', 2025, 1),
    ('A2', 2025, 2),
    ('A2', 2026, 1),
    ('A2', 2026, 2),
    ('A3', 2025, 1),
    ('A3', 2025, 2),
    ('A3', 2026, 1),
    ('A3', 2026, 2),
]

data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
s = pd.Series(data, index=index)
print(s)

(A1, 2025, 1)     1
(A1, 2025, 2)     2
(A1, 2026, 1)     3
(A1, 2026, 2)     4
(A2, 2025, 1)     5
(A2, 2025, 2)     6
(A2, 2026, 1)     7
(A2, 2026, 2)     8
(A3, 2025, 1)     9
(A3, 2025, 2)    10
(A3, 2026, 1)    11
(A3, 2026, 2)    12
dtype: int64


In [106]:
mi = pd.MultiIndex.from_tuples(index)
s = s.reindex(mi)
print(s)

A1  2025  1     1
          2     2
    2026  1     3
          2     4
A2  2025  1     5
          2     6
    2026  1     7
          2     8
A3  2025  1     9
          2    10
    2026  1    11
          2    12
dtype: int64


In [107]:
print(s.loc[:, 2025])

A1  1     1
    2     2
A2  1     5
    2     6
A3  1     9
    2    10
dtype: int64


In [108]:
df = s.unstack()
print(df)

          1   2
A1 2025   1   2
   2026   3   4
A2 2025   5   6
   2026   7   8
A3 2025   9  10
   2026  11  12


In [109]:
df1 = pd.DataFrame(
    {'jan' : s.loc[:,:,1],
     'feb' : s[:,:,2],
     'mar' : s[:,:,1] + s[:,:,2]}
)
print(df1)

         jan  feb  mar
A1 2025    1    2    3
   2026    3    4    7
A2 2025    5    6   11
   2026    7    8   15
A3 2025    9   10   19
   2026   11   12   23


In [110]:
print(df1.loc[:,'mar'], end='\n\n')
print(df1.loc['A1'], end='\n\n')
print(df1.loc['A1', 'feb'])

A1  2025     3
    2026     7
A2  2025    11
    2026    15
A3  2025    19
    2026    23
Name: mar, dtype: int64

      jan  feb  mar
2025    1    2    3
2026    3    4    7

2025    2
2026    4
Name: feb, dtype: int64


In [111]:
print(df1.loc[['A1', 'A2'], 'feb'], end='\n\n')
print(df1.loc[['A1', 'A2'], ['jan', 'feb']])

A1  2025    2
    2026    4
A2  2025    6
    2026    8
Name: feb, dtype: int64

         jan  feb
A1 2025    1    2
   2026    3    4
A2 2025    5    6
   2026    7    8


In [112]:
print(df1.iloc[[1,0], [1,1]])

         feb  feb
A1 2026    4    4
   2025    2    2


In [113]:
rng = np.random.default_rng(1)
df = pd.DataFrame(
    rng.random(size=(4, 2)),
    index=[['A1', 'A1', 'A2', 'A2'], [2025, 2026, 2025, 2026]],
    columns=['jan','feb']
)
print(df)

              jan       feb
A1 2025  0.511822  0.950464
   2026  0.144160  0.948649
A2 2025  0.311831  0.423326
   2026  0.827703  0.409199


In [114]:
data = {
    ('A1', 2025, 1): 1,
    ('A1', 2025, 2): 2,
    ('A1', 2026, 1): 3,
    ('A1', 2026, 2): 4,
    ('A2', 2025, 1): 5,
    ('A2', 2025, 2): 6,
    ('A2', 2026, 1): 7,
    ('A2', 2026, 2): 8,
    ('A3', 2025, 1): 9,
    ('A3', 2025, 2): 10,
    ('A3', 2026, 1): 11,
    ('A3', 2026, 2): 12,
}

s = pd.Series(data)
print(s)

A1  2025  1     1
          2     2
    2026  1     3
          2     4
A2  2025  1     5
          2     6
    2026  1     7
          2     8
A3  2025  1     9
          2    10
    2026  1    11
          2    12
dtype: int64


In [138]:
# Ways how to create MultiIndex
# 1. from_tuples
index =[
    ('A1', 2025),
    ('A1', 2026),
    ('A2', 2025),
    ('A2', 2026)
]
    
index = pd.MultiIndex.from_tuples(index)
print(index)

MultiIndex([('A1', 2025),
            ('A1', 2026),
            ('A2', 2025),
            ('A2', 2026)],
           )


In [127]:
# 2. from_arrays
index = pd.MultiIndex.from_arrays([['A1', 'A1', 'A2', 'A2'], [2025, 2026, 2025, 2026]])
print(index)

MultiIndex([('A1', 2025),
            ('A1', 2026),
            ('A2', 2025),
            ('A2', 2026)],
           )


In [128]:
# 3. from_product
index = pd.MultiIndex.from_product([['A1', 'A2'], [2025, 2026]])
print(index)

MultiIndex([('A1', 2025),
            ('A1', 2026),
            ('A2', 2025),
            ('A2', 2026)],
           )


In [141]:
# codes
index = pd.MultiIndex(
    levels = [['A1', 'A2'], [2025, 2026]],
    codes = [[0,0,1,1], [0,1,0,1]]
)
print(index)

MultiIndex([('A1', 2025),
            ('A1', 2026),
            ('A2', 2025),
            ('A2', 2026)],
           )


In [142]:
'''Мульиндекс можно использовать в index при создании DataFrame 
или перестроить уже существующий DataFrame через reindex()
'''

'Мульиндекс можно использовать в index при создании DataFrame \nили перестроить уже существующий DataFrame через reindex()\n'

In [166]:
df = pd.DataFrame(
    rng.uniform(0, 1, size=(4,2)),
    index = pd.MultiIndex.from_product([['A1', 'A2'], [2025, 2026]])
)

df.index.names = ['property', 'year'] # Бывает удобно дать названия столбцам или строкам в MultiIndex
print(df)

                      0         1
property year                    
A1       2025  0.482049  0.181831
         2026  0.535238  0.905734
A2       2025  0.148626  0.571032
         2026  0.087851  0.303097


In [178]:
mi1 = pd.MultiIndex.from_product([['A1', 'A2'], [2025, 2026]], names=['shops', 'years'])
print(mi1)

mi2 = pd.MultiIndex.from_product([['B1', 'B2', 'B3'],  ['jan', 'feb']], names=['shop', 'month'])
print(mi2)

rng = np.random.default_rng()
data = rng.uniform(0, 1, size=(4,6)) # rng.random(4,6) - the same*
print(data, end='\n\n')

df = pd.DataFrame(data, index=mi1, columns=mi2)
print(df)

MultiIndex([('A1', 2025),
            ('A1', 2026),
            ('A2', 2025),
            ('A2', 2026)],
           names=['shops', 'years'])
MultiIndex([('B1', 'jan'),
            ('B1', 'feb'),
            ('B2', 'jan'),
            ('B2', 'feb'),
            ('B3', 'jan'),
            ('B3', 'feb')],
           names=['shop', 'month'])
[[0.37003987 0.61921694 0.33918849 0.14195167 0.5678792  0.5890667 ]
 [0.19550175 0.77342287 0.64954548 0.91240862 0.06635447 0.03291437]
 [0.99148888 0.68509918 0.89437992 0.2693966  0.14559917 0.59289078]
 [0.37267931 0.87369341 0.95409203 0.67829012 0.47365912 0.8869059 ]]

shop               B1                  B2                  B3          
month             jan       feb       jan       feb       jan       feb
shops years                                                            
A1    2025   0.370040  0.619217  0.339188  0.141952  0.567879  0.589067
      2026   0.195502  0.773423  0.649545  0.912409  0.066354  0.032914
A2    2025   0.991489