In [1]:
#Конспект Сережина Владимира
import sys
import array
import numpy as np
import random

In [2]:
'''динамическая типизация - причина 
по которой мы отказались от стандартной библиотеки Python и выбрали numpy'''
x = 1
print(type(x))

l = [True, "2", 3.0, 4]
print([type(i) for i in l])

import sys
print(sys.getsizeof(l))

<class 'int'>
[<class 'bool'>, <class 'str'>, <class 'float'>, <class 'int'>]
88


In [3]:
l1 = []
print(type(l1))
print(sys.getsizeof(l1)) #56 байтов ушли на хранение ПУСТО. Python написан на C (который хронит указатели и др.), что приводит к затрате на память

<class 'list'>
56


In [4]:
a1 = array.array('i', [1])
print(type(a1))

print(sys.getsizeof(a1))

<class 'array.array'>
68


In [5]:
print(np.__version__)

1.20.1


In [6]:
a = np.array([1, 2, 3, 4])

In [7]:
l = np.array(a1)

In [8]:
print(sys.getsizeof(a1))
print(sys.getsizeof(l))
#для малого количества данных списки лучше. Но для большого количества - списки numpy выгоднее

68
108


In [9]:
#повышающее поведение типов
a1 = np.array([1, 2, 3, 4])
print(type(a1), a1)

<class 'numpy.ndarray'> [1 2 3 4]


In [10]:
#повышающее поведение типов
a = np.array([1, 2, 3, 4, "a"])
print(type(a), a)

<class 'numpy.ndarray'> ['1' '2' '3' '4' 'a']


In [11]:
#явно задать тип
a = np.array([1.99, 2, 3, 4, 5], dtype = int)
print(type(a), a)

<class 'numpy.ndarray'> [1 2 3 4 5]


In [12]:
#одномерные массивы
a = np.array(range(2, 5))
print(a)

[2 3 4]


In [13]:
#многомерные массивы
a = np.array([range(i, i + 5)] for i in [1, 2, 3])
print(a) #Почему вывел генератор, а не матрицу?

<generator object <genexpr> at 0x0000028C471ECCF0>


In [14]:
# "с нуля"
print(np.zeros(10, dtype=int))

[0 0 0 0 0 0 0 0 0 0]


In [15]:
# из 1
print(np.ones((3, 5), dtype=float))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
# предопределённое значение
print(np.full((3, 3), 3.1416))

[[3.1416 3.1416 3.1416]
 [3.1416 3.1416 3.1416]
 [3.1416 3.1416 3.1416]]


In [17]:
# линейная последовательность чисел
print(np.arange(0, 20, 2))
print(np.arange(0, 20, 3))

[ 0  2  4  6  8 10 12 14 16 18]
[ 0  3  6  9 12 15 18]


In [18]:
# в интервале с одинаковыми промежутками
print(np.linspace(0, 1, 11))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [19]:
# равномерное распределение от 0 до 1
print(np.random.random((2, 4)))

[[0.15118801 0.78204846 0.45082207 0.25204446]
 [0.30257681 0.21028201 0.60411152 0.62916026]]


In [20]:
print(np.random.normal((2, 4)))

[2.70821368 4.11775759]


In [21]:
# равномерное распределение от x до y
print(np.random.randint(0, 5, (2, 2)))

[[1 3]
 [3 0]]


In [22]:
# единичная матрица
print(np.eye(10, dtype=int))

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]


In [23]:
#Типы данных
print(np.zeros(10, dtype=int))
print(np.zeros(10, dtype='int16'))
print(np.zeros(10, dtype=np.int16))

[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]


In [24]:
print(a1, type(a1), a1.dtype) # python
print(a2, type(a2), a2.dtype) # np
print(a3, type(a3), a3.dtype) # np

# a1 = np.zeros(10, dtype = int16)
# NameError: name 

[1 2 3 4] <class 'numpy.ndarray'> int32


NameError: name 'a2' is not defined

In [ ]:
# ТЕМЫ КУРСА

# Numerical (числовой) Python = NumPy
# - атрибуты массивов
# - индексация
# - срезы
# - изменение формы
# - объединение и разбиение

In [ ]:
# Атрибуты: ndim - число размерностей, shape - размер каждой размерности, size - общий размер массива

np.random.seed(1)

x1 = np.random.randint(10, size= 3)
print(x1)
print(x1.ndim, x1.shape, x1.size)

In [ ]:
x2 = np.random.randint(10, size= (3, 2))
print(x2)
print(x2.ndim, x2.shape, x2.size)

In [ ]:
x3 = np.random.randint(10, size= (3, 2, 4))
print(x3)
print(x3.ndim, x3.shape, x3.size)

In [ ]:
# Индексация (Indexing)
a = np.array([1, 2, 3, 4, 5])
print(a[0])
print(a[-2])

In [ ]:
# Многомерные (Multidimensional arrays)
a = np.array([[0, 1], [2, 3]])
print(a)
print(a[0,0])
print(a[-1,-2])

a[1,0] = 100
print(a)

In [ ]:
# вставки

a = np.array([1, 2, 3, 4, 5])
print(a.dtype)

In [ ]:
a[0] = 3.14
print(a)
print(a.dtype)

In [ ]:
a.dtype = float
print(a)
print(a.dtype)
# Мораль: не менять типы на ходу

In [ ]:
# Срезы - подмассив массива [начало:конец:*шаг]
a = np.array([1, 2, 3, 4, 5])

print(a[:3])
print(a[3:])
print(a[1:4])

In [ ]:
a = np.array([1, 2, 3, 4, 5])
print(a[1])

In [ ]:
#Slices of multidensional massives
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
print()
print(a[:2, :3])
print()
print(a[::-1, ::-1])
print()
# 1 3
# 5 7 
# 9 11
print(a[:, ::2])
print()
print(a[:, 0]) # рисуется как одномерный массив, хоть это и столбец!
print()
print(a[0, :]) # only first line

In [ ]:
# Срезы в Python - копии подмассивов, в NumPy - представления (view)
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

a_2x2 = a[:2, :2]
print(a_2x2)

a_2x2[0, 0] = 999
print(a) #оригинальный массив поменялся!

a_2x2 = a[:2, :2].copy()
a_2x2[0, 0] = 1001 # Массив a не поменялся!
print(a)

In [ ]:
# Форма массива. Изменение
a = np.arange(1, 13)
print(a, a.shape, a.ndim)

In [ ]:
print(a[3])
print(a[11])

In [ ]:
a1 = a.reshape(1, 12)
print(a1, a1.shape, a1.ndim)

In [ ]:
print(a1[0, 3])
print(a1[0, 11])

In [ ]:
a2 = a.reshape(2, 6)
print(a2, a2.shape, a2.ndim)

In [ ]:
# 12 = 2*6=2*2*3= 1*12*1*1
a3 = a.reshape(2, 2, 3)
print(a3, a3.shape, a3.ndim, a3.size)
print()
print(a3[0, 1, 2])

In [ ]:
# 12 = 2*6=2*2*3= 1*12*1*1
a4 = a.reshape(1, 12, 1, 1)
print(a4, a4.shape, a4.ndim)
print(a4[0, 3, 0, 0])

In [ ]:
a5 = a.reshape((2, 6)) # Хороший тон - писать размерности в виде кортежа!
print(a5, a5.shape, a5.ndim)
print(a5[1, 5])

In [ ]:
a6 = a.reshape((2, 6), order="F") # Заполнение матрицы поменяли с горизонтального на вертикальный!
print(a6, a6.shape, a6.ndim)
print(a6[1, 4])

In [ ]:
a7 = a.reshape((2, 6), order="C") # Транспонируем матрицу
print(a7, a7.shape, a7.ndim)

In [ ]:
a = np.arange(1, 13) #С точки зрения NumPy, a - не матрциа.
print(a, a.shape, a.ndim)

a1 = a.reshape(1, 12)
print(a1, a1.shape, a1.ndim) #This's already a matrix

In [ ]:
a2 = a[np.newaxis, :] # Adding a new axis
print(a2, a2.shape, a2.ndim)