In [1]:
#Конспект Сережина Владимира
import sys
import array
import numpy as np
import random
import timeit

In [2]:
'''динамическая типизация - причина 
по которой мы отказались от стандартной библиотеки Python и выбрали numpy'''
x = 1
print(type(x))

l = [True, "2", 3.0, 4]
print([type(i) for i in l])

import sys
print(sys.getsizeof(l))

<class 'int'>
[<class 'bool'>, <class 'str'>, <class 'float'>, <class 'int'>]
88


In [3]:
l1 = []
print(type(l1))
print(sys.getsizeof(l1)) #56 байтов ушли на хранение ПУСТО. Python написан на C (который хронит указатели и др.), что приводит к затрате на память

<class 'list'>
56


In [4]:
a1 = array.array('i', [1])
print(type(a1))

print(sys.getsizeof(a1))

<class 'array.array'>
68


In [5]:
print(np.__version__)

1.20.1


In [6]:
a = np.array([1, 2, 3, 4])

In [7]:
l = np.array(a1)

In [8]:
print(sys.getsizeof(a1))
print(sys.getsizeof(l))
#для малого количества данных списки лучше. Но для большого количества - списки numpy выгоднее

68
108


In [9]:
#повышающее поведение типов
a1 = np.array([1, 2, 3, 4])
print(type(a1), a1)

<class 'numpy.ndarray'> [1 2 3 4]


In [10]:
#повышающее поведение типов
a = np.array([1, 2, 3, 4, "a"])
print(type(a), a)

<class 'numpy.ndarray'> ['1' '2' '3' '4' 'a']


In [11]:
#явно задать тип
a = np.array([1.99, 2, 3, 4, 5], dtype = int)
print(type(a), a)

<class 'numpy.ndarray'> [1 2 3 4 5]


In [12]:
#одномерные массивы
a = np.array(range(2, 5))
print(a)

[2 3 4]


In [13]:
#многомерные массивы
a = np.array([range(i, i + 5)] for i in [1, 2, 3])
print(a) #Почему вывел генератор, а не матрицу?

<generator object <genexpr> at 0x000001C90577AC10>


In [14]:
# "с нуля"
print(np.zeros(10, dtype=int))

[0 0 0 0 0 0 0 0 0 0]


In [15]:
# из 1
print(np.ones((3, 5), dtype=float))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
# предопределённое значение
print(np.full((3, 3), 3.1416))

[[3.1416 3.1416 3.1416]
 [3.1416 3.1416 3.1416]
 [3.1416 3.1416 3.1416]]


In [17]:
# линейная последовательность чисел
print(np.arange(0, 20, 2))
print(np.arange(0, 20, 3))

[ 0  2  4  6  8 10 12 14 16 18]
[ 0  3  6  9 12 15 18]


In [18]:
# в интервале с одинаковыми промежутками
print(np.linspace(0, 1, 11))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [19]:
# равномерное распределение от 0 до 1
print(np.random.random((2, 4)))

[[0.2760682  0.76360769 0.27288768 0.9676161 ]
 [0.1821261  0.87554555 0.22362727 0.90902231]]


In [20]:
print(np.random.normal((2, 4)))

[2.1709925  5.99720904]


In [21]:
# равномерное распределение от x до y
print(np.random.randint(0, 5, (2, 2)))

[[2 1]
 [3 3]]


In [22]:
# единичная матрица
print(np.eye(10, dtype=int))

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]


In [23]:
#Типы данных
print(np.zeros(10, dtype=int))
print(np.zeros(10, dtype='int16'))
print(np.zeros(10, dtype=np.int16))

[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]


In [24]:
# ТЕМЫ КУРСА

# Numerical (числовой) Python = NumPy
# - атрибуты массивов
# - индексация
# - срезы
# - изменение формы
# - объединение и разбиение

In [25]:
# Атрибуты: ndim - число размерностей, shape - размер каждой размерности, size - общий размер массива

np.random.seed(1)

x1 = np.random.randint(10, size= 3)
print(x1)
print(x1.ndim, x1.shape, x1.size)

[5 8 9]
1 (3,) 3


In [26]:
x2 = np.random.randint(10, size= (3, 2))
print(x2)
print(x2.ndim, x2.shape, x2.size)

[[5 0]
 [0 1]
 [7 6]]
2 (3, 2) 6


In [27]:
x3 = np.random.randint(10, size= (3, 2, 4))
print(x3)
print(x3.ndim, x3.shape, x3.size)

[[[9 2 4 5]
  [2 4 2 4]]

 [[7 7 9 1]
  [7 0 6 9]]

 [[9 7 6 9]
  [1 0 1 8]]]
3 (3, 2, 4) 24


In [28]:
# Индексация (Indexing)
a = np.array([1, 2, 3, 4, 5])
print(a[0])
print(a[-2])

1
4


In [29]:
# Многомерные (Multidimensional arrays)
a = np.array([[0, 1], [2, 3]])
print(a)
print(a[0,0])
print(a[-1,-2])

a[1,0] = 100
print(a)

[[0 1]
 [2 3]]
0
2
[[  0   1]
 [100   3]]


In [30]:
# вставки

a = np.array([1, 2, 3, 4, 5])
print(a.dtype)

int32


In [31]:
a[0] = 3.14
print(a)
print(a.dtype)

[3 2 3 4 5]
int32


In [32]:
a.dtype = float
print(a)
print(a.dtype)
# Мораль: не менять типы на ходу

ValueError: When changing to a larger dtype, its size must be a divisor of the total size in bytes of the last axis of the array.

In [33]:
# Срезы - подмассив массива [начало:конец:*шаг]
a = np.array([1, 2, 3, 4, 5])

print(a[:3])
print(a[3:])
print(a[1:4])

[1 2 3]
[4 5]
[2 3 4]


In [34]:
a = np.array([1, 2, 3, 4, 5])
print(a[1])

2


In [35]:
#Slices of multidensional massives
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
print()
print(a[:2, :3])
print()
print(a[::-1, ::-1])
print()
# 1 3
# 5 7 
# 9 11
print(a[:, ::2])
print()
print(a[:, 0]) # рисуется как одномерный массив, хоть это и столбец!
print()
print(a[0, :]) # only first line

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[1 2 3]
 [5 6 7]]

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]

[[ 1  3]
 [ 5  7]
 [ 9 11]]

[1 5 9]

[1 2 3 4]


In [36]:
# Срезы в Python - копии подмассивов, в NumPy - представления (view)
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

a_2x2 = a[:2, :2]
print(a_2x2)

a_2x2[0, 0] = 999
print(a) #оригинальный массив поменялся!

a_2x2 = a[:2, :2].copy()
a_2x2[0, 0] = 1001 # Массив a не поменялся!
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2]
 [5 6]]
[[999   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[999   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [37]:
# Форма массива. Изменение
a = np.arange(1, 13)
print(a, a.shape, a.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12] (12,) 1


In [38]:
print(a[3])
print(a[11])

4
12


In [39]:
a1 = a.reshape(1, 12)
print(a1, a1.shape, a1.ndim)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]] (1, 12) 2


In [40]:
print(a1[0, 3])
print(a1[0, 11])

4
12


In [41]:
a2 = a.reshape(2, 6)
print(a2, a2.shape, a2.ndim)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] (2, 6) 2


In [42]:
# 12 = 2*6=2*2*3= 1*12*1*1
a3 = a.reshape(2, 2, 3)
print(a3, a3.shape, a3.ndim, a3.size)
print()
print(a3[0, 1, 2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] (2, 2, 3) 3 12

6


In [43]:
# 12 = 2*6=2*2*3= 1*12*1*1
a4 = a.reshape(1, 12, 1, 1)
print(a4, a4.shape, a4.ndim)
print(a4[0, 3, 0, 0])

[[[[ 1]]

  [[ 2]]

  [[ 3]]

  [[ 4]]

  [[ 5]]

  [[ 6]]

  [[ 7]]

  [[ 8]]

  [[ 9]]

  [[10]]

  [[11]]

  [[12]]]] (1, 12, 1, 1) 4
4


In [44]:
a5 = a.reshape((2, 6)) # Хороший тон - писать размерности в виде кортежа!
print(a5, a5.shape, a5.ndim)
print(a5[1, 5])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] (2, 6) 2
12


In [45]:
a6 = a.reshape((2, 6), order="F") # Заполнение матрицы поменяли с горизонтального на вертикальный!
print(a6, a6.shape, a6.ndim)
print(a6[1, 4])

[[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]] (2, 6) 2
10


In [46]:
a7 = a.reshape((2, 6), order="C") # Транспонируем матрицу
print(a7, a7.shape, a7.ndim)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] (2, 6) 2


In [47]:
a = np.arange(1, 13) # С точки зрения NumPy, a - не матрциа.
print(a, a.shape, a.ndim)

a1 = a.reshape(1, 12)
print(a1, a1.shape, a1.ndim) #This's already a matrix

[ 1  2  3  4  5  6  7  8  9 10 11 12] (12,) 1
[[ 1  2  3  4  5  6  7  8  9 10 11 12]] (1, 12) 2


In [48]:
a2 = a[np.newaxis, :] # Adding a new axis
print(a2, a2.shape, a2.ndim)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]] (1, 12) 2


In [49]:
# Слияние и разбинение массива

# Одномерные
x = np.array([1, 2, 3])
y = np.array([4, 5])
z = np.array([6])

xyz = np.concatenate([x, z, y])
print(xyz)

[1 2 3 6 4 5]


In [50]:
# Двумерные
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])

xy1 = np.concatenate([x, y])
print(xy1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [51]:
xy2 = np.concatenate([x, y], axis = 1)
print(xy2)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [52]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])

print(np.vstack([x, y]), end = '\n\n') # axis = 0

print(np.dstack([x, y]), end = '\n\n') 

print(np.hstack([x, y])) # axis = 1

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [53]:
# Разбиение массивов
xy = np.vstack([x, y])
print(xy)

print(np.split(xy, [0, 3], axis = 0), end = '\n\n') # По первой оси
print(np.split(xy, [1], axis = 1), end = '\n\n') # По второй оси
print(np.hsplit(xy, [1])) # hsplit - сокращённо split(hstack); dsplit, vsplit

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[array([], shape=(0, 3), dtype=int32), array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), array([[10, 11, 12]])]

[array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])]

[array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])]


In [54]:
z = np.dstack([x, y])
print(z, end = '\n\n')
print(np.dsplit(z, [1]))

[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]

[array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]]), array([[[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])]


In [55]:
# Универсальные функции - быстрее циклов for and while
x = np.arange(1, 10)
print(x)

[1 2 3 4 5 6 7 8 9]


In [56]:
def f(x):
    out = np.empty(len(x))
    for i in range(len(x)):
        out[i] = 1.0 / x[i]
    return out

In [57]:
print(f(x))
print(1.0 / x)

[1.         0.5        0.33333333 0.25       0.2        0.16666667
 0.14285714 0.125      0.11111111]
[1.         0.5        0.33333333 0.25       0.2        0.16666667
 0.14285714 0.125      0.11111111]


In [58]:
print(timeit.timeit(stmt="f(x)", globals=globals())) #Работает на порядок дольше!
print(timeit.timeit(stmt="1.0 / x", globals=globals()))

15.661086799999993
0.8815365000000099


In [59]:
# УФ. Арифметические операции

x = np.arange(5)
print(x)

print(x + 1)
print(x - 1)
print(x * 2)
print(x / 2)
print(x % 3)
print(-x)
print(x**2)

print(x * 2 - 2)

print(x + 1)
print(np.add(x, 1)) # Есть некоторые преимущества

print(abs(x)) # Python
print(np.abs(x)) # It's better
print(np.absolute(x))

[0 1 2 3 4]
[1 2 3 4 5]
[-1  0  1  2  3]
[0 2 4 6 8]
[0.  0.5 1.  1.5 2. ]
[0 1 2 0 1]
[ 0 -1 -2 -3 -4]
[ 0  1  4  9 16]
[-2  0  2  4  6]
[1 2 3 4 5]
[1 2 3 4 5]
[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]


In [60]:
# УФ. Тригонометрические функции
# sin, cos, tan, ctg, arccos, arcsin, arctan, arcctg

# УФ. Показательные и логарифмы
# exp, power, log, log2, log10

x = [0, 0.0001, 0.001, 0.01, 0.1]

In [61]:
print("exp = ", np.exp(x))
print("exp - 1= ", np.expm1(x))

exp =  [1.         1.00010001 1.0010005  1.01005017 1.10517092]
exp - 1=  [0.00000000e+00 1.00005000e-04 1.00050017e-03 1.00501671e-02
 1.05170918e-01]


In [62]:
print("log(x) = ", np.log(x))
print("log(1+x) = ", np.log1p(x))

log(x) =  [       -inf -9.21034037 -6.90775528 -4.60517019 -2.30258509]
log(1+x) =  [0.00000000e+00 9.99950003e-05 9.99500333e-04 9.95033085e-03
 9.53101798e-02]


<ipython-input-62-c37fd14eada2>:1: RuntimeWarning: divide by zero encountered in log
  print("log(x) = ", np.log(x))


In [63]:
# УФ.
x = np.arange(10)
print(x)
y = 10 * x
print(y)

z = np.empty(len(x))
np.multiply(x, 10, out=z)
print(z)

[0 1 2 3 4 5 6 7 8 9]
[ 0 10 20 30 40 50 60 70 80 90]
[ 0. 10. 20. 30. 40. 50. 60. 70. 80. 90.]


In [64]:
x = np.arange(5)
z = np.zeros(10)
print(x) 
print(z)
z[::2] = x*10
print(z)

[0 1 2 3 4]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0. 10.  0. 20.  0. 30.  0. 40.  0.]


In [65]:
z = np.zeros(10)
np.multiply(x, 10, out=z[::2])
print(z)

[ 0.  0. 10.  0. 20.  0. 30.  0. 40.  0.]


In [75]:
# Сводные показатели
x = np.arange(1, 5)
print(x)
print(np.add.reduce(x))
print(np.add.accumulate(x))
print(np.multiply.accumulate(x))
print(np.subtract.accumulate(x))
print(np.sum(x))
print(np.cumsum(x))
print(np.prod(x))
print(np.cumprod(x))

[1 2 3 4]
10
[ 1  3  6 10]
[ 1  2  6 24]
[ 1 -1 -4 -8]
10
[ 1  3  6 10]
24
[ 1  2  6 24]


In [81]:
x = np.arange(1, 10)
print(np.add(x, x))
print(np.multiply.outer(x, x))

[ 2  4  6  8 10 12 14 16 18]
[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]


In [125]:
# Агрегирование данных
np.random.seed(3)
s = np.random.random(10)
print(sum(s)) # python
print(np.sum(s))

4.67502334813787
4.67502334813787


In [144]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(sum(a)) # python

print(np.sum(a))
print(np.sum(a, axis=0)) # 0 - vertical direction (columns)
print(np.sum(a, axis=1)) # 1 - horizontal direction (rows)

print(type(a))
print(a.sum())
print(a.sum(0))
print(a.sum(1))

print(sum(a, 1)) # установили начальное значение суммы

[ 7  9 11 13 15]
55
[ 7  9 11 13 15]
[15 40]
<class 'numpy.ndarray'>
55
[ 7  9 11 13 15]
[15 40]
[ 8 10 12 14 16]


In [146]:
# min, max - analogically to the 'sum'
print(np.max(a))

10


In [167]:
# mean, std, var, median, argmin, argmax, percentile, any, all
# nan*

# Not a number element - NaN

# Транслирование (broadcasting)

a = np.array([1, 2, 3])
b = np.array([5])
print(a + b)
# 6, 7, 8

print(a + 5)
# 6, 7, 8

[6 7 8]
[6 7 8]
